name: CI-CD sell-notes

on:
    push:
        branches:
            - main

env: 
    IMAGE_NAME: sell-notes-739204
    CONTAINER_REGISTRY: 932065333859.dkr.ecr.us-east-1.amazonaws.com/sell-notes-739204

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build Docker image
              run: |
                docker build -t ${{ env.CONTAINER_REGISTRY }}:latest .

            - name: Push Docker image to ECR
              run: |
                docker push ${{ env.CONTAINER_REGISTRY }}:latest